[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "krakenex>=2.2.2",
    "numpy>=2.3.1",
    "pykrakenapi>=0.3.2",
    "requests>=2.32.4",
]
